export const LANGUAGES: Record<string, string> = {
  // European languages
  sq: 'Albanian',
  hy: 'Armenian',
  bs: 'Bosnian (Latin)',
  bg: 'Bulgarian',
  ca: 'Catalan',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  en: 'English',
  et: 'Estonian',
  fo: 'Faroese',
  fi: 'Finnish',
  fr: 'French',
  'fr-ca': 'French (Canada)',
  de: 'German',
  el: 'Greek',
  is: 'Icelandic',
  ga: 'Irish',
  it: 'Italian',
  lv: 'Latvian',
  lt: 'Lithuanian',
  mk: 'Macedonian',
  mt: 'Maltese',
  nb: 'Norwegian',
  pl: 'Polish',
  pt: 'Portuguese (Brazil)',
  'pt-pt': 'Portuguese (Portugal)',
  ro: 'Romanian',
  ru: 'Russian',
  'sr-Cyrl': 'Serbian (Cyrillic)',
  'sr-Latn': 'Serbian (Latin)',
  sk: 'Slovak',
  sl: 'Slovenian',
  es: 'Spanish',
  sv: 'Swedish',
  tr: 'Turkish',
  uk: 'Ukrainian',
  cy: 'Welsh',
  // Non-European languages
  af: 'Afrikaans',
  am: 'Amharic',
  ar: 'Arabic',
  as: 'Assamese',
  az: 'Azerbaijani (Latin)',
  bn: 'Bangla',
  ba: 'Bashkir',
  eu: 'Basque',
  yue: 'Cantonese (Traditional)',
  lzh: 'Chinese (Literary)',
  'zh-Hans': 'Chinese Simplified',
  'zh-Hant': 'Chinese Traditional',
  prs: 'Dari',
  dv: 'Divehi',
  fj: 'Fijian',
  fil: 'Filipino',
  gl: 'Galician',
  ka: 'Georgian',
  gu: 'Gujarati',
  ht: 'Haitian Creole',
  he: 'Hebrew',
  hi: 'Hindi',
  mww: 'Hmong Daw (Latin)',
  hu: 'Hungarian',
  id: 'Indonesian',
  ikt: 'Inuinnaqtun',
  iu: 'Inuktitut',
  'iu-Latn': 'Inuktitut (Latin)',
  ja: 'Japanese',
  kn: 'Kannada',
  kk: 'Kazakh',
  km: 'Khmer',
  'tlh-Latn': 'Klingon',
  'tlh-Piqd': 'Klingon (plqaD)',
  ko: 'Korean',
  ku: 'Kurdish (Central)',
  kmr: 'Kurdish (Northern)',
  ky: 'Kyrgyz (Cyrillic)',
  lo: 'Lao',
  mg: 'Malagasy',
  ms: 'Malay (Latin)',
  ml: 'Malayalam',
  mi: 'Maori',
  mr: 'Marathi',
  'mn-Cyrl': 'Mongolian (Cyrillic)',
  'mn-Mong': 'Mongolian (Traditional)',
  my: 'Myanmar',
  ne: 'Nepali',
  or: 'Odia',
  ps: 'Pashto',
  fa: 'Persian',
  pa: 'Punjabi',
  otq: 'Queretaro Otomi',
  sm: 'Samoan (Latin)',
  so: 'Somali (Arabic)',
  sw: 'Swahili (Latin)',
  ty: 'Tahitian',
  ta: 'Tamil',
  tt: 'Tatar (Latin)',
  te: 'Telugu',
  th: 'Thai',
  bo: 'Tibetan',
  ti: 'Tigrinya',
  to: 'Tongan',
  tk: 'Turkmen (Latin)',
  hsb: 'Upper Sorbian',
  ur: 'Urdu',
  ug: 'Uyghur (Arabic)',
  uz: 'Uzbek (Latin)',
  vi: 'Vietnamese',
  yua: 'Yucatec Maya',
  zu: 'Zulu',
};

export const RTLeftLanguages = [
  'ar',
  'arc',
  'az',
  'dv',
  'he',
  'ku',
  'fa',
  'ur',
];

export type LanguageCode = keyof typeof LANGUAGES;
export const getLanguageName = (code: LanguageCode): string => {
  return LANGUAGES[code];
};
